server:
  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    port: 6379
    password: root
    host: 192.168.64.33
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 #连接池中最大空闲连接
        min-idle: 0 #连接池中最小空闲连接
        max-wait: 1000 #连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100 #关闭超时时间


login:
  try-limit: 5
  key:
    # 多少分钟后，重新计算错误次数
    expire-min: 2
  lock:
    # 锁定多少小时
    hour: 1
